// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrganizationStructureService.Data.DataContexts;

#nullable disable

namespace OrganizationStructureService.Data.Migrations
{
    [DbContext(typeof(OrgStrDataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("OrganizationStructureService.Data.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("RoleId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("OrganizationStructureService.Data.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Head of IT"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Security Engineer Manager"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Network Engineer"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Senior Cloud Architect"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Help Desk Manager"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Security Engineer"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Cloud Architect"
                        },
                        new
                        {
                            Id = 8,
                            Name = "IT Help Desk Technician"
                        });
                });

            modelBuilder.Entity("OrganizationStructureService.Data.Models.Person", b =>
                {
                    b.HasOne("OrganizationStructureService.Data.Models.Person", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OrganizationStructureService.Data.Models.Role", "Role")
                        .WithMany("Persons")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OrganizationStructureService.Data.Models.Role", b =>
                {
                    b.Navigation("Persons");
                });
#pragma warning restore 612, 618
        }
    }
}
